Fix helm configuration
api-platform/api-platform pull request #1630
Opened 2020-08-24 22:03 UTC by vincentchalamon

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       |
| License       | MIT
| Doc PR        |

2020-08-28 16:25 UTC, dunglas requested changes

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/Chart.yaml
> +    - name: external-dns
To remove, this shouldn't be included in this chart

2020-08-28 16:25 UTC, dunglas commented on api/docker/nginx/conf.d/default.tmpl
> +        # Bigger buffer size to handle cache invalidation headers expansion
Why this change? Shouldn't it be reverted?

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/templates/php-deployment.yaml
> -            initialDelaySeconds: 120
Why?

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/templates/tests/test-connection.yaml
> -  name: $fullName-test-connection
What's the benefit of this change?

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/templates/php-deployment.yaml
> -            - name: MERCURE_JWT_TOKEN
This change look buggy to me. The Symfony environment variable is `MERCURE_JWT_TOKEN`: https://github.com/symfony/recipes/blob/master/symfony/mercure-bundle/0.1/manifest.json#L12 This must be reverted.

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/values.yaml
> +    - 103.21.244.0/22
I guess that they are Cloudflare's IPs? This should be removed.

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/values.yaml
> +  corsAllowOrigin: "^https?://.*\\.api-platform\\.com$"
this must be reverted, same next line.

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/values.yaml
> +  #url: pgsql://api-platform:!ChangeMe!@example.com/api?serverVersion=10
These changes must be reverted.

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/values.yaml
> +  enabled: true
I wouldn't enable varnish by default.

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/values.yaml
> +  subscribeUrl: https://mercure.api-platform.com/.well-known/mercure
to revert

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/values.yaml
> +  corsAllowedOrigins: "^https?://.*\\.api-platform\\.com$"
to revert

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/values.yaml
> +  enabled: true
to revert, this must not be enabled by default

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/values.yaml
> +    - host: api.api-platform.com
to revert

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/templates/php-deployment.yaml
> -            initialDelaySeconds: 120
same, probably to revert

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/values.yaml
> +    jwtSecret: ""
to revert

2020-08-28 16:25 UTC, dunglas commented on api/docker/nginx/conf.d/default.tmpl
> +        fastcgi_pass "${UPSTREAM}";
This will break dynamic resolution, you should use something like:

```suggestion
        set $upstream "${UPSTREAM}";
        fastcgi_pass $upstream;
```

2020-08-28 16:25 UTC, dunglas commented on api/helm/api/values.yaml
> +  #  cpu: 100m
probably to revert

2020-08-28 17:11 UTC, vincentchalamon commented on api/helm/api/templates/tests/test-connection.yaml
> -  name: $fullName-test-connection
Without it, the variable `$fullName` seems not properly read

2020-09-01 08:50 UTC, dunglas requested changes

2020-09-01 08:50 UTC, dunglas commented on api/helm/api/templates/ingress.yaml
> +              {{- if contains "mercure" $host }}
I'm not a fond of this. Couldn't we change the value instead to have something like the following instead of relying on the hostname?

```
ingresses:
   api: ...
   mercure: ...
```

2020-09-01 08:50 UTC, dunglas commented on api/helm/api/templates/php-deployment.yaml
> -            periodSeconds: 3
This should be kept.

2020-09-01 08:50 UTC, dunglas commented on api/helm/api/templates/php-deployment.yaml
> -            periodSeconds: 3
This should be kept.

2020-09-01 08:50 UTC, dunglas commented on api/helm/api/templates/tests/test-connection.yaml
> +{{- $name := "test-connection" -}}
This variable is unused isn't it? So this could be reverted.

2020-09-01 08:50 UTC, dunglas commented on api/helm/api/values.yaml
> +    type: NodePort
I would keep a `ClusterIP` by default for security. Exposing a service from the outside of the cluster must be a conscious choice from the user.

2020-09-01 08:50 UTC, dunglas commented on api/helm/api/values.yaml
> +    type: NodePort
Same here, a ClusterIP should be used by default.

2020-09-03 09:33 UTC, dunglas commented on admin/Dockerfile
> +EXPOSE 3000
Why is this necessary?

2020-09-03 09:34 UTC, vincentchalamon commented on admin/Dockerfile
> +EXPOSE 3000
I tried locally with nginx-proxy. If the port is not exposed, nginx-proxy cannot map to this container

2020-09-08 17:59 UTC, dunglas commented on admin/Dockerfile
> +EXPOSE 3000
I'm not sure to follow. This container isn't used in production.

2020-09-19 06:47 UTC, vincentchalamon commented on api/helm/api/templates/ingress.yaml
> +              {{- if contains "mercure" $host }}
I removed it cause it should be the choice of the developer to use mercure in this ingress, or directly use the mercure ingress, or another alternative.

2020-09-25 10:08 UTC, soyuka commented on api/helm/api/templates/configmap.yaml
> +  mercure-publish-url: {{ printf "http://%s-mercure/.well-known/mercure" .Release.Name | quote }}
Sure this isn't `https`?

2020-09-25 10:10 UTC, vincentchalamon commented on api/helm/api/templates/configmap.yaml
> +  mercure-publish-url: {{ printf "http://%s-mercure/.well-known/mercure" .Release.Name | quote }}
Well, it seems to work this way on api-platform/demo, so I would say yes

2020-09-25 10:23 UTC, merged

2020-09-25 10:24 UTC, soyuka commented
thanks @vincentchalamon