Add some updates
api-platform/api-platform pull request #1887
Opened 2021-04-20 17:06 UTC by vincentchalamon

| Q             | A
| ------------- | ---
| Branch?       | main
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

2021-04-20 20:51 UTC, dunglas commented on .github/workflows/ci.yml
> +    security-check:
GitHub does this automatically, IMHO this isn't needed because this is only works on GitHub anyway.

2021-04-20 20:53 UTC, dunglas commented on api/config/services_test.yaml
> +services:
Shouldn't this be added in the Flex recipe instead? We synchronize the config files with the official recipes before every release.

2021-04-20 20:53 UTC, vincentchalamon commented on .github/workflows/ci.yml
> +    security-check:
I was wondering about it too, using dependabot, but couldn't find any article about it.

2021-04-20 20:53 UTC, dunglas commented on api/public/robots.txt
> +# www.robotstxt.org/
What's the point of adding this file?

2021-04-20 23:33 UTC, dunglas commented on .github/workflows/ci.yml
> +    security-check:
It's documented here: https://docs.github.com/en/code-security/supply-chain-security/about-alerts-for-vulnerable-dependencies

2021-04-21 15:57 UTC, dunglas requested changes

2021-04-21 15:57 UTC, dunglas commented on api/.gitignore
> -/docker/db/data
These deletions should be reverted isn't it?

2021-04-21 15:57 UTC, dunglas commented on docker-compose.yml
> +    image: ${CONTAINER_REGISTRY_BASE:-ghcr.io/api-platform/api-platform}/php:${CONTAINER_REGISTRY_TAG:-latest}
This must be removed. We don't upload pre-built images to a registry anymore (it is not worth the complexity).

2021-04-21 15:57 UTC, dunglas commented on api/.env.test
> +TRUSTED_HOSTS=^example\.com|localhost$
why this change?

2021-04-21 15:57 UTC, dunglas commented on .github/workflows/ci.yml
> +  push:
Can you preserve the indentation please? IIRC it's in sync with GitHub's best practices.

2021-04-21 16:00 UTC, vincentchalamon commented on docker-compose.yml
> +    image: ${CONTAINER_REGISTRY_BASE:-ghcr.io/api-platform/api-platform}/php:${CONTAINER_REGISTRY_TAG:-latest}
But how can we name the images built from `docker-compose build` before deploy?

2021-04-21 16:01 UTC, vincentchalamon commented on api/.env.test
> +TRUSTED_HOSTS=^example\.com|localhost$
The WebTestCase defines the client host to http://localhost, but the ApiTestCase defines it to http://example.com

2021-04-21 16:02 UTC, vincentchalamon commented on .github/workflows/ci.yml
> +  push:
Well, the .editorconfig is wrong so: https://github.com/api-platform/api-platform/blob/main/.editorconfig#L50-L52

2021-04-22 18:10 UTC, vincentchalamon commented on .github/workflows/ci.yml
> +  push:
Indent with 2 seems already GitHub's best practices:

> In YAML examples, such as actions and workflow files, use two spaces to indent lines within nested lists and block sequences.

https://github.com/github/docs/blob/main/contributing/content-style-guide.md#indentation

2021-04-22 19:13 UTC, dunglas commented on docker-compose.yml
> +    image: ${CONTAINER_REGISTRY_BASE:-ghcr.io/api-platform/api-platform}/php:${CONTAINER_REGISTRY_TAG:-latest}
Why do we need to use `docker-compose` to build the images for k8s?

2021-04-22 19:15 UTC, dunglas commented on api/Dockerfile
> +RUN wget -O /usr/local/bin/php-fpm-healthcheck https://raw.githubusercontent.com/renatomefi/php-fpm-healthcheck/master/php-fpm-healthcheck; \
Can we copy (and adapt) this script instead of relying on an external repository please?

2021-04-22 19:16 UTC, dunglas commented on api/Dockerfile
> +ENV FCGI_CONNECT=/var/run/php/php-fpm.sock
Why do we need this env var?

2021-04-22 19:16 UTC, vincentchalamon commented on docker-compose.yml
> +    image: ${CONTAINER_REGISTRY_BASE:-ghcr.io/api-platform/api-platform}/php:${CONTAINER_REGISTRY_TAG:-latest}
How to you recommend to build Docker images for k8s? :thinking:

2021-04-22 19:18 UTC, vincentchalamon commented on api/Dockerfile
> +ENV FCGI_CONNECT=/var/run/php/php-fpm.sock
For php-fpm-healthcheck to use this sock instead of the default value `localhost:9000`

2021-04-22 22:07 UTC, dunglas commented on api/Dockerfile
> +ENV FCGI_CONNECT=/var/run/php/php-fpm.sock
Maybe could we hardcore this as default value in the script?

2021-04-23 11:28 UTC, vincentchalamon commented on api/.env.test
> +TRUSTED_HOSTS=^example\.com|localhost$
https://github.com/api-platform/core/issues/4242

2021-04-24 07:52 UTC, dunglas approved these changes

2021-04-24 07:52 UTC, dunglas commented on .github/workflows/ci.yml
> +
This blank line can be removed for consistency.

2021-04-24 07:52 UTC, dunglas commented on api/Dockerfile
> +HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD ["php-fpm-healthcheck", "-v"]
Why do we need to use the verbose mode?

2021-04-24 07:52 UTC, dunglas commented on api/docker/php/php-fpm-healthcheck
> +    FPM_STATUS=$(env -i REQUEST_METHOD="$REQUEST_METHOD" SCRIPT_NAME="$SCRIPT_NAME" SCRIPT_FILENAME="$SCRIPT_FILENAME" "$FCGI_CMD_PATH" -bind -connect "$1" 2> /dev/null)
Isn't this doing basically the same thing as the script we currently have? I don't understand why our script fails but not this one.

2021-04-24 07:52 UTC, dunglas commented on helm/api-platform/templates/deployment.yaml
> +                - -v
Same here, do we need the verbose output?

2021-04-24 11:02 UTC, vincentchalamon commented on api/docker/php/php-fpm-healthcheck
> +    FPM_STATUS=$(env -i REQUEST_METHOD="$REQUEST_METHOD" SCRIPT_NAME="$SCRIPT_NAME" SCRIPT_FILENAME="$SCRIPT_FILENAME" "$FCGI_CMD_PATH" -bind -connect "$1" 2> /dev/null)
Found. It's fixed in this PR (rollbacked to docker-healthcheck)

2021-05-03 07:14 UTC, dunglas commented on api/Dockerfile
> -
This could maybe be reverted to reduce the diff.

2021-05-03 07:15 UTC, dunglas commented on api/config/packages/framework.yaml
> -    trusted_hosts: '%env(TRUSTED_HOSTS)%'
This must be reverted.

2021-05-03 07:24 UTC, dunglas requested changes

2021-05-03 07:24 UTC, dunglas commented on helm/api-platform/templates/ingress.yaml
>  {{- if .Values.ingress.enabled -}}
We should use @sagikazarmark's definition instead: https://github.com/sagikazarmark/helm-charts/blob/master/charts/caddy/templates/ingress.yaml

2021-05-03 07:24 UTC, dunglas commented on pwa/Dockerfile
> +ARG ENTRYPOINT
AFAIU, it's useless.

2021-05-03 07:24 UTC, dunglas commented on pwa/config/entrypoint.ts
> +export const ENTRYPOINT = typeof window === "undefined" ? process.env.ENTRYPOINT : window.origin;
We should add a default value for the `ENTRYPOINT` env var here or in the `docker-compose.yaml`.

2021-05-20 14:57 UTC, dunglas approved these changes

2021-06-14 13:01 UTC, merged

2021-06-14 13:07 UTC, dunglas commented
Thanks @vincentchalamon! Great work.