feat: update composer.json for symfony 5.3, bump php 8.0 => 8.0.2
api-platform/api-platform pull request #1931
Opened 2021-06-06 11:05 UTC by Chris53897

| Q             | A
| ------------- | ---
| Branch?       | main->
| License       | MIT

Bump symfony 5.2 to 5.3

Bump >=8.0 to >=8.0.2
Symfony 6 is using this, so i guess they avoid some bugs in 8.0.0 and 8.0.1
https://github.com/symfony/symfony/blob/6.0/composer.json

2021-06-06 11:26 UTC, Chris53897 commented
Argh. i just want a title or whatever is needed so the UnitTests will start :(

2021-06-10 12:31 UTC, soyuka commented
the commit message should respsect the conventional commits spec: https://www.conventionalcommits.org/en/v1.0.0/

2021-06-11 13:25 UTC, vincentchalamon commented
You should also update the recipes: `composer sync-recipes --force`
Some config files will be updated, please check for some useless files that may be deleted.

2021-06-14 14:25 UTC, vincentchalamon requested changes

2021-06-14 14:25 UTC, vincentchalamon commented on api/config/packages/framework.yaml
> +when@test:
You should remove the api/config/packages/test/framework.yaml file

2021-06-14 14:25 UTC, vincentchalamon commented on api/config/packages/routing.yaml
> +when@prod:
You should remove the api/config/packages/prod/routing.yaml file

2021-06-14 14:25 UTC, vincentchalamon commented on api/config/packages/twig.yaml
> +when@test:
You should remove the api/config/packages/test/twig.yaml file

2021-06-14 14:25 UTC, vincentchalamon commented on api/config/routes/framework.yaml
> +when@dev:
You should remove the api/config/routes/dev/framework.yaml & twig.yaml files

2021-06-14 14:50 UTC, merged