Fixes #1847 "Docker: Launch the php image with a non root user"
api-platform/api-platform pull request #2189
Opened 2022-05-04 09:45 UTC by anthony-o

| Q             | A
| ------------- | ---
| Branch?       | main for features / current stable version branch for bug fixes 
| Tickets       | #1847
| License       | MIT
| Doc PR        | api-platform/docs#... 

This PR will launch all the commands as the host user (at least, the owner id of file 'composer.json') which is convenient to be able not to generate files as "root" on the host sources : the developer using the api-platform tarball will be able to modify those files without chowning them.

One should also modify the documentation at https://api-platform.com/docs/distribution/#plugging-the-persistence-system in order to change all the `docker-compose exec` references to `docker-compose exec -T -u $(id -u)` so that all the files created will be with the host's user id and not `root`.

2022-07-20 14:26 UTC, vincentchalamon requested changes
Hi @anthony-o,

Thanks for your contribution! You pointed something important related to security, it's always good to talk about it and improve it. Thanks!

For security reasons, it's recommended to run a Docker container using another user than root. Your approach only concerns some commands, and requires to pass an option on any `docker compose exec` command, which can be error prone.

I recommend to define a non-root user in the Dockerfile, by default using uid/gid 1000 (which is the most common uid/gid of the default user on many os) which can be overriden through Docker build-args, and set this user as default on the Dockerfile. Doing so will configure and run any file and command from this user, and prevent security issues.

But beware cause this can also implies some issues like permissions on volumes, etc.

2022-08-03 06:50 UTC, dunglas requested changes
I wonder if the files shouldn't be owned by the built-in user `www-data`?

2022-08-03 06:50 UTC, dunglas commented on api/docker/php/docker-entrypoint.sh
> +	set -- su-exec $USER_ID php-fpm "$@"
This isn't necessary. The official image is already designed to run FPM processes as non-root: https://github.com/docker-library/php/issues/70

2022-08-03 06:54 UTC, dunglas commented
See also: https://github.com/Sylius/Sylius-Standard/pull/242#issuecomment-407333686

The current situation seems to be the best compromise we can make.

2022-10-07 10:37 UTC, anthony-o commented on api/docker/php/docker-entrypoint.sh
> +	set -- su-exec $USER_ID php-fpm "$@"
Yes but I need to run the PHP script I developed as my current user ID when developing (for example to have read & write access to my folders) and by default it is running as another user id, so the files created when I execute my PHP script are not accessible by my current user ID (as a developer). This is a problem while developing... and this is why I wrote this patch.

2022-10-07 10:40 UTC, anthony-o commented
> See also: [Sylius/Sylius-Standard#242 (comment)](https://github.com/Sylius/Sylius-Standard/pull/242#issuecomment-407333686)

I agree with this comment and this is why I want to patch the entrypoint to take into account a given env variable containing the user id rather than defining it directly in the Dockerfile.

2026-05-18 12:56 UTC, soyuka commented
https://github.com/api-platform/api-platform/issues/2987

2026-05-18 12:56 UTC, closed without merging