feat: add native Xdebug support
api-platform/api-platform pull request #2226
Opened 2022-08-02 20:59 UTC by dunglas

| Q             | A
| ------------- | ---
| Branch?       | main
| Tickets       | n/a
| License       | MIT
| Doc PR        | todo

See https://github.com/dunglas/symfony-docker/pull/271

2022-08-03 07:24 UTC, vincentchalamon requested changes
We could also add the `launch.json` file for VSCode:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "pathMappings": {
              "/srv/api": "${workspaceRoot}/api"
            }
        }
    ]
}
```
(file to test, I'm not 100% sure about its location and if it misses a `port` option)

2022-08-03 07:24 UTC, vincentchalamon commented on api/docker/php/conf.d/api-platform.dev.ini
> +xdebug.client_host = 'host.docker.internal'
```suggestion
zend_extension = xdebug.so
xdebug.start_with_request = yes
xdebug.client_host = 'host.docker.internal'
```

2022-08-03 08:07 UTC, dunglas commented on api/docker/php/conf.d/api-platform.dev.ini
> +xdebug.client_host = 'host.docker.internal'
Adding the xdebug extension is done automatically, and I don't think that's a good idea to profile every requests by default.

2022-08-03 08:08 UTC, dunglas commented
To not bloat this skeleton and keep it as minimal as possible, I would prefer having the VSCode configuration in the docs instead.

2022-08-03 08:09 UTC, vincentchalamon approved these changes

2022-08-03 16:13 UTC, maxhelias approved these changes

2022-08-04 12:06 UTC, vincentchalamon commented on api/docker/php/docker-entrypoint.sh
> +	#mkdir -p var/cache var/log
```suggestion
```

2022-08-04 12:09 UTC, vincentchalamon commented on pwa/Dockerfile
> +VOLUME /usr/src/pwa/node_modules
Isn't it breaking?

2022-08-04 12:37 UTC, dunglas commented on pwa/Dockerfile
> +VOLUME /usr/src/pwa/node_modules
No, it's removing this: https://github.com/api-platform/api-platform/commit/92b6f245d9b6a415fa9c4ad58dac084e8a2f35a0

2022-08-04 12:39 UTC, vincentchalamon approved these changes

2022-08-04 13:01 UTC, merged