Update Dockerfile
api-platform/api-platform pull request #2340
Opened 2022-12-09 11:59 UTC by jibla

This is the fix for issue #2339

2022-12-09 12:07 UTC, dunglas requested changes

2022-12-09 12:07 UTC, dunglas commented on api/Dockerfile
> +RUN apk add --update linux-headers
Can't this package added to the next RUN instruction instead?

2022-12-09 12:22 UTC, jibla commented on api/Dockerfile
> +RUN apk add --update linux-headers
Sure, it can be, will move there.

2022-12-09 12:50 UTC, jibla commented on api/Dockerfile
> +RUN apk add --update linux-headers
Done.

2022-12-10 14:53 UTC, MWDylanD approved these changes

2022-12-11 10:19 UTC, dunglas requested changes
Thanks! Could you preserve the original indentation please?

2022-12-11 12:23 UTC, jibla commented
@dunglas Fixed.

2022-12-20 09:35 UTC, RubenKruiswijk reviewed
I believe this is the original indentation @dunglas was looking for. :-)

2022-12-20 09:35 UTC, RubenKruiswijk commented on api/Dockerfile
> +        linux-headers \
```suggestion
		linux-headers \
```

2022-12-20 09:35 UTC, RubenKruiswijk commented on api/Dockerfile
> +        acl \
```suggestion
		acl \
```

2022-12-20 09:35 UTC, RubenKruiswijk commented on api/Dockerfile
> +        fcgi \
```suggestion
		fcgi \
```

2022-12-20 09:35 UTC, RubenKruiswijk commented on api/Dockerfile
> +        file \
```suggestion
		file \
```

2022-12-20 09:35 UTC, RubenKruiswijk commented on api/Dockerfile
> +        gettext \
```suggestion
		gettext \
```

2022-12-20 09:35 UTC, RubenKruiswijk commented on api/Dockerfile
> +        git \
```suggestion
		git \
```

2022-12-20 09:35 UTC, RubenKruiswijk commented on api/Dockerfile
> +    ;
```suggestion
	;
```

2022-12-20 11:29 UTC, jibla commented
@RubenKruiswijk applied all your suggestions. Thanks.

2022-12-20 14:56 UTC, dunglas commented
Hi @jibla. Thanks for your work on this. I (obviously) had the same issue while working on #2344, and it looks like this package is only necessary for XDebug, so it could be added only to the dev image: https://github.com/api-platform/api-platform/pull/2344/files#diff-21ee93e31c9cec7a5f33b680622da377c451b62b6c44eac6d9550eade41beb47R116

2022-12-20 19:39 UTC, dunglas commented
Included in #2344. Thanks again @jibla!

2022-12-20 19:39 UTC, closed without merging