feat(httpcache): souin integration
api-platform/api-platform pull request #2487
Opened 2023-07-22 00:25 UTC by darkweak

| Q             | A
| ------------- | ---
| Branch?       | main
| Tickets       | Closes https://github.com/api-platform/api-platform/issues/1947
| License       | MIT
| Doc PR        | https://github.com/api-platform/docs/pull/1720

Obsoletes #2383

2023-08-23 16:01 UTC, vincentchalamon commented on api/docker/caddy/Caddyfile
> +    cache
```suggestion
    cache {
        api {
            souin
        }
    }
```

2023-08-23 16:43 UTC, darkweak commented
Hey, do you have two different Caddyfiles (one for prod and another one for dev)?
On debug environment, I suggest to update the Cache-Status name (using the directive `cache_name`) it will replace the default `Souin` value (e.g. `Souin; hit; ttl="99"..` become `Your-debug-cache-name; hit; ...`). Unfortunately it's not possible to set a debug header.

2023-08-24 08:13 UTC, vincentchalamon commented
Is something like that would do the work?
```
# Caddyfile
{
    order cache before rewrite
    cache {
        api {
            souin
        }
    }
}

{$CADDY_CACHE}

# ...
```
```yaml
# docker-compose.prod.yml
services:
    caddy:
        environment:
            CADDY_CACHE: cache
```
I'm wondering if the `caddy.api.souin` declaration would cause issues even in dev mode. WDYT?

2023-08-24 08:19 UTC, darkweak commented
Why don't you link a `Caddyfile.prod` in your `docker-compose.prod.yml` instead of the default `Caddyfile`? Is it mandatory to have only one Caddyfile?

2023-08-24 09:10 UTC, vincentchalamon commented
Using a `Caddyfile.prod` requires to duplicate the content from `Caddyfile`, or use [import](https://caddyserver.com/docs/caddyfile/directives/import) feature and juggle with Caddyfiles files such as:
```
# Caddyfile.prod

import Caddyfile.dev

cache
```
```
# Dockerfile

RUN mv /etc/caddy/Caddyfile /etc/caddy/Caddyfile.dev
COPY --link docker/caddy/Caddyfile.prod /etc/caddy/Caddyfile
```

I'm working on an implementation here: https://github.com/api-platform/demo/commit/02e5026171a4561ae9793935b78b67e06f695e1e

2023-08-24 09:58 UTC, dunglas commented
Having a single Caddyfile will help with maintenance. It's possible to inject any global options in `CADDY_DEBUG`. I opened #2502 to improve this.

2023-08-24 11:50 UTC, vincentchalamon requested changes
Nice integration. Main issue: cache should only be enabled on prod env. Check https://github.com/api-platform/demo/commit/73977b3bcbcead417f05e6f13f9cafe77b81b096 for example

2023-08-24 11:50 UTC, vincentchalamon commented on api/config/packages/api_platform.yaml
> +            enabled: true
Cache invalidation should only be enabled on prod env

2023-08-24 11:50 UTC, vincentchalamon commented on api/config/packages/api_platform.yaml
> +            max_age: 0
HTTP Cache Headers should only be set on prod env

2023-08-24 11:50 UTC, vincentchalamon commented on api/docker/caddy/Caddyfile
> +    cache {
Cache should only be enabled on prod env

2023-08-25 08:27 UTC, dunglas commented on api/Dockerfile
> +# ADD --chmod=500 https://caddyserver.com/api/download?os=linux&arch=$TARGETARCH&p=github.com/dunglas/mercure/caddy&p=github.com/dunglas/vulcain/caddy&p=github.com/darkweak/souin/plugins/caddy /usr/b
IMHO you could load the module. No need for a comment. People not wanting this feature will remove it.

2023-09-12 11:22 UTC, vincentchalamon requested changes

2023-09-12 11:22 UTC, vincentchalamon commented on api/config/packages/api_platform.yaml
> +            urls: ['%env(SOUIN_API_URL)%']
```suggestion
            urls: ['%env(SOUIN_API_URL)%']

```

2023-09-12 11:22 UTC, vincentchalamon commented on api/.env
> +SOUIN_API_URL=http://caddy/souin-api/souin
A declared env var without being used, especially in dev/test environments, will throw an error in Symfony commands

2023-09-12 11:22 UTC, vincentchalamon commented on api/config/packages/api_platform.yaml
> +            max_age: 0
Comment still valid for `max_age` header

2023-09-12 11:22 UTC, vincentchalamon commented on api/docker/caddy/Caddyfile
> +cache
Should be enabled through an env var:
```suggestion
{$CADDY_CACHE}
```
Then, declare this env var in docker-compose.prod.yml and helm chart to only enable cache on production

2023-09-12 11:22 UTC, vincentchalamon commented on docker-compose.yml
> +      CADDY_GLOBAL_OPTIONS: |
Do not enable cache on dev

2023-09-12 11:30 UTC, darkweak commented
https://github.com/darkweak/souin/issues/new if you have issues using it.

2026-05-18 12:56 UTC, soyuka commented
https://github.com/api-platform/api-platform/issues/2987

2026-05-18 12:56 UTC, closed without merging